# Generated by Django 4.1.5 on 2023-06-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_desc_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='streetNumber',
        ),
    ]
