# Generated by Django 4.1.5 on 2023-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_street_address_streetname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='subscribed',
            field=models.IntegerField(),
        ),
    ]
