# Generated by Django 4.1.5 on 2023-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sale_deliverydate_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
