ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER gowest_admin IDENTIFIED BY gowest;
GRANT CONNECT, RESOURCE TO gowest_admin;
ALTER USER gowest_admin DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
